name: phone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  crop: ^0.5.5
  image: ^4.3.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  flutter_contacts: ^1.1.9+2
  country_code_picker: ^3.1.0
  intl: ^0.19.0
  objectbox: ^4.0.3
  objectbox_flutter_libs: any
  path_provider: ^2.1.5
  speech_to_text: ^7.0.0
  flutter_sound: ^9.21.1
  dio: ^5.8.0+1
  lottie: ^3.3.1
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.5.2
  share_plus: ^10.1.4
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.1
  fluttertoast: ^8.2.12
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/animations/listening.json
    - assets/api.env
flutter_intl:
  enabled: true
